### PR TITLE
Started converting Slides to MD.

### PR DESCRIPTION
**Pull request by coyoteJohn**
I started adding markdown by taking information from the slides. I also created an example Excel workbook to accompany the slides. I can pick up on this later in the weekend. 

In the meantime, I am looking for feedback. Any suggestions are welcome. 

Finally, can someone explain why the students need to learn AVERAGEIF and AVERAGEIFS?

### CODE REVIEW

**Review by JohanBester — COMMENTED** [review]
Looking good so far

**Review by matsinet — APPROVED** [review]

**Review by JohanBester — APPROVED** [review]
I approve  :)

**Review by matsinet — APPROVED** [review]

**Review by matsinet — COMMENTED** [review]
In the future there, is no need to include 'DAP' in the file names as the overall repository is exclusively for DAP.

**Review by JohanBester — APPROVED** [review]
Looking great!
I approve

**Comment by JohanBester** [comment]
I am closing this PR as it is old and outdated.
We will pull down master to development and start new PRs for new Changes

**Pull request closed without merging**
