### PR TITLE
Dap sql

### PR DESCRIPTION
**Pull request by coyoteJohn**
---
name: SQL Section 7 Updates
about: ''
title: 'DAP-###: {Issue Title}'
assignees: ''

---

Issue Link: [DAP-###](https://github.com/savvy-coders/dap-curriculum/issues/###)

@JohanBester I need to find my notes on the right way to do this - but at least this allows you to see the section 7 updates.

### CODE REVIEW

**Comment by JohanBester** [comment]
Hi John,
It looks like this Pull Request is against the Main branch. That is not correct.
Please change it to pull into the Development branch.
Thanks

**Comment by coyoteJohn** [comment]
Okay - the target branch has been updated.

**Review by JohanBester — APPROVED** [review]
I do not see any glaring issues here 
I approve!

**Comment by coyoteJohn** [comment]
Thanks Johan, one week down!

**Pull request merged**
